### ISSUE TITLE
Panic with MariaDB 10.6

### ISSUE THREAD

**Issue by laeo** [a8m/entspatial#2]
```
=== RUN   Example_Point
--- FAIL: Example_Point (0.07s)
panic: insert node to table "locations": Error 4079: Illegal parameter data type char for operation 'st_geometryfromwkb' [recovered]
	panic: insert node to table "locations": Error 4079: Illegal parameter data type char for operation 'st_geometryfromwkb'

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc000145c68, {0x0, 0x0}, 0x0?, 0x0, {0x12a7600, 0xc000066460})
	/usr/local/Cellar/go/1.18.1/libexec/src/testing/example.go:91 +0x4e5
testing.runExample.func2()
	/usr/local/Cellar/go/1.18.1/libexec/src/testing/run_example.go:59 +0x11c
panic({0x12a7600, 0xc000066460})
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207
github.com/a8m/entspatial/ent.(*LocationCreate).SaveX(...)
	/Users/laeo/Works/TryCode/entspatial/ent/location_create.go:113
github.com/a8m/entspatial.Example_Point()
	/Users/laeo/Works/TryCode/entspatial/example_test.go:37 +0x7e5
testing.runExample({{0x12ed2f7, 0xd}, 0x1315480, {0x12fdaff, 0x4a}, 0x0})
	/usr/local/Cellar/go/1.18.1/libexec/src/testing/run_example.go:63 +0x28d
testing.runExamples(0xc000145e58, {0x14e3b40?, 0x1, 0x0?})
	/usr/local/Cellar/go/1.18.1/libexec/src/testing/example.go:44 +0x186
testing.(*M).Run(0xc000116460)
	/usr/local/Cellar/go/1.18.1/libexec/src/testing/testing.go:1721 +0x689
main.main()
	_testmain.go:47 +0x1aa
exit status 2
FAIL	github.com/a8m/entspatial	2.648s
```

I did a lot of researches, but i cant find the way to solve it, can you help me solve this problem?

**Comment by laeo** [comment]
OK, i got the same issue with existed [issue](https://github.com/paulmach/orb/issues/61), will wait the related PR to merge.
